//@version=6
indicator("VWAP", "vwap", format = format.percent, overlay = true)

var int inputBarsPercentile = input.int(500, "Bars Percentile")
var string inputVwapAnchor = input.string("D", "Vwap Anchor Period")

var displayMode = display.data_window + display.pane
var displayOverlayMode = display.pane


oc2 = (open + close) / 2

vwap = ta.vwap(oc2, timeframe.change(inputVwapAnchor))

plot(vwap, display = displayOverlayMode, force_overlay = true)
