//@version=6
indicator("LQDT Monitor", "LQDT", format = format.price, overlay = true)

debugLabelUp(txt,overlay=true) =>
    label.new(bar_index, high, txt, yloc = yloc.abovebar, style = label.style_arrowdown, force_overlay = overlay, textcolor = color.black)
debugLabelDn(txt,overlay=true) =>
    label.new(bar_index, low, txt, yloc = yloc.belowbar, style = label.style_arrowup, force_overlay = overlay, textcolor = color.black)


var float dayprice = na

var float dayhigh = na
var float daylow = na

daychange = timeframe.change("D")

if daychange
    if false
        debugLabelDn(str.format("{0}\n{1}\n{2}\n{3}\n{4}\n{5}\n{6}",
             strPrice(high),
             strPrice(syminfo.mintick), 
             strPrice(syminfo.pointvalue), 
             strPrice(syminfo.mincontract), 
             strPrice(syminfo.minmove),
             strPrice(syminfo.pricescale),
             strPrice(syminfo.minmove/syminfo.pricescale)
             ))
    dayprice := open
    dayhigh := dayprice
    daylow := dayhigh - syminfo.mintick

bool pressure_down = false
bool pressure_up = false

float phigh = na
float plow = na
phigh := high == low ? phigh[1] : high
plow := high == low ? plow[1] : low
//plot(phigh, style = plot.style_circles, color = color.new(color.green,0), linewidth = 12)
//plot(plow, style = plot.style_circles, color = color.new(color.red,0), linewidth = 8)

pressure_down := not daychange and
     plow < plow[1] or
     (plow == plow[1] and phigh == phigh[1] and phigh - plow > syminfo.mintick and plow < daylow)
pressure_up := not daychange and
     plow > plow[1] or (phigh > phigh[1] and plow == plow[1]) or
     (plow == plow[1] and phigh == phigh[1] and phigh - plow > syminfo.mintick and phigh > dayhigh)

plotchar(pressure_down, char = "v", location = location.abovebar, color = color.new(color.red,50), size = size.normal)
plotchar(pressure_up, char = "^", location = location.belowbar, color = color.new(color.green,0), size = size.normal)


// ALERTS

strPrice(float v) =>
    var _strPriceScale = str.repeat("#",math.ceil(math.log10(syminfo.pricescale)))
    str.format("{0,number,"+"#."+_strPriceScale+"}",v)


if pressure_down
    alert(str.format("LQDT Pressure DOWN : {0}->{1}", strPrice(plow[1]), strPrice(plow)), alert.freq_once_per_bar)
if pressure_up
    alert(str.format("LQDT Pressure UP : {0}->{1}", strPrice(plow[1]), strPrice(plow)), alert.freq_once_per_bar)
