//@version=6
indicator("Trend by Linreg Slope", "linreg_slope", precision = 3, timeframe = "3")

int period = input.int(100, "period linreg", inline = "01")

oc2 = (open + close) / 2
source_linreg = oc2

float slope = ta.linreg(source_linreg, period, 0) - ta.linreg(source_linreg, period, 1)
color plotColor = slope > 0 ? color.teal : color.maroon


plot(ta.linreg(source_linreg, period, 0), "linreg", force_overlay = true)
plot(slope, "slope", plotColor, 1, plot.style_area)
