//@version=6
indicator("Price Spike Detector", "price_spike", format = format.price, overlay = false)

barsP99 = input.int(1500, "Percentile Bars", inline = "01")
percP99 = input.float(99.75, "P99 %", inline = "01")
barsCum = input.int(3, "Cumulative Bars", inline = "01")
// barsCum2 = input.int(3, "Bars x2", inline = "01")
dispP99 = input.bool(true, "Levels P99", group = "Show/Hide", inline = "1")
dispCum = input.bool(true, "Cumulative", group = "Show/Hide", inline = "2")
dispCumP99 = input.bool(true, "P99", group = "Show/Hide", inline = "2")
dispBg = input.bool(true, "Highlight Background", group = "Show/Hide")

price_change_positive = high > close[1] ? high-close[1] : 0
price_change_negative = low < close[1] ? low-close[1] : 0

price_change_positive_p99 = ta.percentile_nearest_rank(price_change_positive, barsP99, percP99)
price_change_negative_p99 = ta.percentile_nearest_rank(-price_change_negative, barsP99, percP99)
price_change_positive_p100 = ta.percentile_nearest_rank(price_change_positive, barsP99, 100)
price_change_negative_p100 = ta.percentile_nearest_rank(-price_change_negative, barsP99, 100)

colorchangepos = switch
    price_change_positive_p100 <= price_change_positive => color.new(color.purple, 50)
    price_change_positive_p99 <= price_change_positive => color.new(color.blue, 50)
    => color.new(color.gray, 50)
colorchangeneg = switch
    price_change_negative <= -price_change_negative_p100 => color.new(color.purple, 50)
    price_change_negative <= -price_change_negative_p99 => color.new(color.blue, 50)
    => color.new(color.gray, 50)

plot(price_change_positive, "+change", style = plot.style_columns, color=colorchangepos)
plot(price_change_negative, "-change", style = plot.style_columns, color=colorchangeneg)

plot(price_change_positive_p99, "+changeP99", color = color.new(color.gray,50), display = dispP99 ? display.all : display.none)
plot(-price_change_negative_p99, "-changeP99", color = color.new(color.gray,50), display = dispP99 ? display.all : display.none)

// bgcolor_price_change = switch
//     price_change_positive >= price_change_positive_p99 => color.new(color.green, 85)
//     price_change_negative >= price_change_negative_p99 => color.new(color.red, 85)
//     => na
// bgcolor(bgcolor_price_change, display = dispBg ? display.all : display.none)
// bgcolor(bgcolor_price_change, force_overlay = true, display = dispBg ? display.all : display.none)

// // Cumulative

cum_pos = math.sum(price_change_positive, barsCum)
cum_neg = math.sum(price_change_negative, barsCum)

plot(cum_pos, "+cum", color = color.new(color.olive,75), display = dispCum ? display.all : display.none)
plot(cum_neg, "-cum", color = color.new(color.olive,75), display = dispCum ? display.all : display.none)

// cum_positive_p99 = ta.percentile_nearest_rank(cum_pos, inputLengthPercentile, 99)
// cum_negative_p99 = ta.percentile_nearest_rank(cum_neg, inputLengthPercentile, 99)

// plot(cum_positive_p99, "+cumP99", color = color.new(color.olive,75), display = dispCum and dispCumP99 ? display.all : display.none)
// plot(-cum_negative_p99, "-cumP99", color = color.new(color.olive,75), display = dispCum and dispCumP99 ? display.all : display.none)

// bgcolor_cum = switch
//     cum_pos >= cum_positive_p99 => color.new(color.green, 85)
//     cum_neg >= cum_negative_p99 => color.new(color.red, 85)
//     => na
// bgcolor(bgcolor_cum, force_overlay = true, display = dispBg ? display.all : display.none)

