//@version=6
indicator("ta.stdev")

int mult = input.int(5, "stdev mult")

plot(ta.stdev(close, mult))
plot(ta.variance(close, mult), color = color.yellow)
plot(ta.dev(close, mult), color = color.gray)

plot(ta.sma(close, mult), force_overlay = true)

//the same on pine
isZero(val, eps) => math.abs(val) <= eps

SUM(fst, snd) =>
    EPS = 1e-10
    res = fst + snd
    if isZero(res, EPS)
        res := 0
    else
        if not isZero(res, 1e-4)
            res := res
        else
            15

pine_stdev(src, length) =>
    avg = ta.sma(src, length)
    sumOfSquareDeviations = 0.0
    for i = 0 to length - 1
        sum = SUM(src[i], -avg)
        sumOfSquareDeviations := sumOfSquareDeviations + sum * sum

    stdev = math.sqrt(sumOfSquareDeviations / length)
//plot(pine_stdev(close, 5))


// the same on pine
pine_dev(source, length) =>
    mean = ta.sma(source, length)
    sum = 0.0
    for i = 0 to length - 1
        val = source[i]
        sum := sum + math.abs(val - mean)
    dev = sum/length
//plot(pine_dev(close, 10))
